[package]
name = "lophat"
version = "0.14.0"
edition = "2024"
description = "Lockfree Persistent Homology Algorithm Toolbox"
readme = "README.md"
homepage = "https://github.com/tomchaplin/lophat"
repository = "https://github.com/tomchaplin/lophat"
license = "MIT"
keywords = ["chain-complex", "persistence-module", "persistent-homology", "tda", "topology"]
categories = ["mathematics", "science"]
exclude = ["docs/**/*", "scripts/**/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "lib"]
name = "lophat"

[dependencies]
bit-set = "0.11.1"
macro_rules_attribute = { version = "0.2.3", optional = true }
pinboard = "2.2.0"
pyo3 = { version = "0.29.3", features = ["experimental-inspect"], optional = true }
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"], optional = true }

[dev-dependencies]
ciborium = "0.2.2"
proptest = "1.7.0"

[features]
default = ["local_thread_pool", "python-module", "serde"]
local_thread_pool = []
python-module = ["dep:macro_rules_attribute", "dep:pyo3"]
serde = ["dep:serde"]

[lints.clippy]
cargo = { level = "warn", priority = -1 }
tabs_in_doc_comments = "allow"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(rust_analyzer)"] }
