[project]
name = "lophat"
requires-python = ">=3.12"
classifiers = [
	"Programming Language :: Python :: Implementation :: CPython",
	"Programming Language :: Python :: Implementation :: PyPy",
	"Programming Language :: Rust",
]
dynamic = ["version"]

[dependency-groups]
dev = [
	"pyrefly>=1.3.2",
	"ruff>=0.16.10",
	"tombi>=1.7.3",
]
benchmark = [
	"gudhi>=3.11",
	"numpy>=2.0",
	"pytest-benchmark>=5.3.0",
	"tadasets>=0.2.1",
	{ include-group = "test" },
]
test = [
	"pytest>=8.3",
]

[build-system]
requires = ["maturin>=1.15.0"]
build-backend = "maturin"

[tool.maturin]
locked = true
profile = "release"

[tool.pyrefly]
preset = "default"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
testpaths = ["tests"]

[tool.ruff]
line-length = 100

[tool.ruff.format]
indent-style = "tab"
docstring-code-format = true
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = ["ALL"]
ignore = [
	# General
	"CPY",  # flake8-copyright/missing-copyright-notice: requires copyright notices within each Python file
	"ERA",  # eradicate: disallows commented code
	"COM812",  # flake8-commas/missing-trailing-comma: requires trailing commas on multiline function calls
	"W191",  # pycodestyle/tab-indentation: disallows tab indentation
	"D206",  # pydocstyle/docstring-tab-indentation: disallows tab indentation in docstring
	"E111",  # pycodestyle/indentation-with-invalid-multiple: forces indentation to be a multiple of 4 spaces
	"E114",  # pycodestyle/indentation-with-invalid-multiple-comment: same as above for comments
	"E117",  # pycodestyle/over-indented: disallows more than 4 spaces of indentation
	"D203",  # pydocstyle/incorrect-blank-line-before-class: requires blank line before class docstring
	"PLR0913",  # pylint/too-many-arguments: too many arguments in function signature
	"PYI021",  # flake8-pyi/docstring-in-stub: disallows docstrings in stub files (not good for extension modules)
	"TD003",  # flake8-todos/missing-todo-link: disallows todos without an issue link
	"ANN401",  # flake8-annotations/any-type: disallows type 'Any' in function signatures
	"ANN003",  # flake8-annotations/missing-type-kwargs: disallows missing types for keyword args dictionary
	"FIX002",  # flake8-fixme/line-contains-todo: checks for TODO comments
]

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = [
	"S101",  # flake8-bandit: disallows use of assert statements
	"PLR2004",  # pylint: disallows magic values
	"INP001",  # pylint: test folder does not need __init__.py
	"D",  # pydocstyle: tests do not need docs
]
"**/__init__.py" = [
	"F401",  # pyflakes: disallows unused imports
	"F403",  # pyflakes: disallows wildcard imports
]
"**.pyi" = ["ALL"]
"docs/**.py" = [
	"INP001",  # pylint: docs folder does not need __init__.py
	"D",  # pydocstyle: doc setup files do not need docs
]
"examples/**.py" = [
	"INP001",  # pylint: docs folder does not need __init__.py
	"D",  # pydocstyle: doc setup files do not need docs
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true
split-on-trailing-comma = false

[tool.ruff.lint.flake8-implicit-str-concat]
allow-multiline = true

[tool.tombi.format.rules]
indent-style = "tab"
line-width = 100

[tool.uv.config-settings]
"maturin.build-args" = "--generate-stubs"
